name: example_project
description: "A new Flutter project."


publish_to: 'none'













version: 1.0.0+1

environment:
  sdk: ^3.5.3







dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.7.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.5
  fluttertoast: ^8.2.5
  flutter_screenutil: ^5.9.1
  intl: any
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  freezed: ^2.4.3
  freezed_annotation: ^2.4.1
  flutter_svg: any
  provider: any
  flutter_local_notifications: ^17.2.3
  pinput: ^5.0.0
  percent_indicator: ^4.2.3
  mask_text_input_formatter: ^2.9.0
  animated_segmented_tab_control: ^2.0.0
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.15.0
  qr_flutter: ^4.1.0
  auto_size_text: ^3.0.0
  salomon_bottom_bar: ^3.3.2
  web_socket_channel: ^3.0.1
  go_router: ^14.3.0
  url_launcher: ^6.3.0
  dropdown_button2: ^2.3.9
  flutter_background_service: ^5.0.10
  flutter_background: any
  sim_card_info: ^1.0.2
  permission_handler: ^11.3.1
  audioplayers: ^6.1.0
  google_maps_flutter: ^2.9.0
  libphonenumber_plugin: ^0.3.3
  flutter_screen_lock: ^9.1.0
  local_auth: ^2.3.0
  table_calendar: ^3.1.2
  fl_chart: any
  xml: ^6.3.0
  path_drawing: ^1.0.1
  geolocator: any
  alice: ^0.4.2
  image_picker: any
  svg_flutter:
  photo_manager: ^3.5.1
  flutter_image_compress: any
  photo_manager_image_provider: ^2.1.1



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/login/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
